version: '3'
services:
  mongodb:
    image: mongo
    command: mongod
    ports:
      - 27017

  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb

  client:
    build: ./app
    links:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb:27017/billy